//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranYonetim.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyonlar
    {
        public int RezervasyonID { get; set; }
        public int MasaID { get; set; }
        public System.DateTime RezervasyonTarihi { get; set; }
        public int RezervasyonSaatAraligi { get; set; }
        public int KisiSayisi { get; set; }
    
        public virtual Masalar Masalar { get; set; }
    }
}
